"""Topological ML Toolkit public Python API."""

from .core import (
    BackendMetadata,
    BettiNumbers,
    PersistenceDiagram,
    PersistencePair,
    available_backends,
    persistent_homology,
    select_backend,
    time_delay_embedding,
)
from .backends import (
    BackendAdapter,
    BackendSelectionResult,
    BackendUnavailableError,
    backend_adapter,
    backend_adapters,
    select_backend_adapter,
)
from .asm import (
    AsmBuildResult,
    AsmDistanceResult,
    AsmNativeBackend,
    CpuFeatureProbe,
    build_asm_native_backend,
    load_asm_native_backend,
)
from .features import (
    BettiCurve,
    PHFeaturizer,
    PersistenceImage,
    TopologySignature,
    activation_signature,
    point_cloud_signature,
)
from .families import TopologyFamily, topology_families, topology_family, topology_family_coverage_matrix
from .gui import write_dashboard
from .native import (
    CppNativeBackend,
    NativeBackendUnavailable,
    NativeBuildResult,
    build_cpp_native_backend,
    load_cpp_native_backend,
)
from .tensor import (
    TensorAlgebraElement,
    TensorBundleSpec,
    bundle_metric_matrix,
    interop_add,
    interop_bundle,
    tensor_bundle_signature_features,
)
from .topology import (
    Cover,
    CoverCell,
    EquivarianceResidual,
    OrbitSignature,
    MapperGraph,
    NerveGraph,
    PathHomotopySignature,
    ScottFixedPointResult,
    SheafResidual,
    StratumSignature,
    WeakConvergenceResidual,
    activation_strata,
    equivariance_residual,
    finite_orbit_signature,
    graph_signature,
    mapper_graph,
    metric_cover,
    nerve_graph,
    path_homotopy_signature,
    scott_fixed_point,
    sheaf_consistency_residual,
    weak_convergence_residual,
)
from .training import TopologyAugmenter, TopologyRandomForestClassifier, topological_sample_weights
from .triton import (
    TritonBackendUnavailable,
    TritonRuntimeStatus,
    triton_pairwise_l2,
    triton_runtime_status,
)

__all__ = [
    "BackendAdapter",
    "BackendMetadata",
    "BackendSelectionResult",
    "BackendUnavailableError",
    "AsmBuildResult",
    "AsmDistanceResult",
    "AsmNativeBackend",
    "BettiNumbers",
    "BettiCurve",
    "Cover",
    "CoverCell",
    "EquivarianceResidual",
    "OrbitSignature",
    "MapperGraph",
    "NerveGraph",
    "PathHomotopySignature",
    "ScottFixedPointResult",
    "CppNativeBackend",
    "CpuFeatureProbe",
    "NativeBackendUnavailable",
    "NativeBuildResult",
    "PHFeaturizer",
    "PersistenceDiagram",
    "PersistencePair",
    "PersistenceImage",
    "SheafResidual",
    "StratumSignature",
    "TensorAlgebraElement",
    "TensorBundleSpec",
    "TopologySignature",
    "TopologyAugmenter",
    "TopologyFamily",
    "TopologyRandomForestClassifier",
    "TritonBackendUnavailable",
    "TritonRuntimeStatus",
    "WeakConvergenceResidual",
    "activation_signature",
    "activation_strata",
    "available_backends",
    "backend_adapter",
    "backend_adapters",
    "build_asm_native_backend",
    "build_cpp_native_backend",
    "equivariance_residual",
    "finite_orbit_signature",
    "bundle_metric_matrix",
    "graph_signature",
    "interop_add",
    "interop_bundle",
    "load_asm_native_backend",
    "load_cpp_native_backend",
    "mapper_graph",
    "metric_cover",
    "nerve_graph",
    "path_homotopy_signature",
    "scott_fixed_point",
    "persistent_homology",
    "point_cloud_signature",
    "select_backend",
    "select_backend_adapter",
    "sheaf_consistency_residual",
    "tensor_bundle_signature_features",
    "time_delay_embedding",
    "topology_families",
    "topology_family",
    "topology_family_coverage_matrix",
    "topological_sample_weights",
    "triton_pairwise_l2",
    "triton_runtime_status",
    "weak_convergence_residual",
    "write_dashboard",
]
