from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Mapping

import numpy as np

from .core import PersistenceDiagram


def write_dashboard(
    path: str | Path,
    *,
    title: str,
    diagram: PersistenceDiagram | None = None,
    feature_matrix: np.ndarray | None = None,
    metadata: Mapping[str, object] | None = None,
) -> Path:
    """Write a self-contained HTML topology inspection dashboard."""

    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        _dashboard_html(
            title=title,
            diagram=diagram,
            feature_matrix=feature_matrix,
            metadata=metadata or {},
        ),
        encoding="utf-8",
    )
    return target


def _dashboard_html(
    *,
    title: str,
    diagram: PersistenceDiagram | None,
    feature_matrix: np.ndarray | None,
    metadata: Mapping[str, object],
) -> str:
    safe_title = html.escape(title)
    diagram_rows = _diagram_rows(diagram)
    matrix_rows = _matrix_rows(feature_matrix)
    metadata_json = html.escape(json.dumps(metadata, indent=2, sort_keys=True, default=str))
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{safe_title}</title>
  <style>
    :root {{
      color-scheme: light;
      --ink: #172026;
      --muted: #5f6b73;
      --line: #d8dee4;
      --panel: #f7f9fb;
      --accent: #0f766e;
    }}
    body {{
      margin: 0;
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      color: var(--ink);
      background: #ffffff;
    }}
    main {{
      max-width: 1120px;
      margin: 0 auto;
      padding: 32px 20px 48px;
    }}
    h1 {{
      margin: 0 0 8px;
      font-size: 32px;
      letter-spacing: 0;
    }}
    h2 {{
      margin: 28px 0 12px;
      font-size: 20px;
      letter-spacing: 0;
    }}
    p {{
      color: var(--muted);
      line-height: 1.55;
    }}
    table {{
      width: 100%;
      border-collapse: collapse;
      background: #ffffff;
      border: 1px solid var(--line);
    }}
    th, td {{
      padding: 10px 12px;
      border-bottom: 1px solid var(--line);
      text-align: left;
      font-variant-numeric: tabular-nums;
    }}
    th {{
      background: var(--panel);
    }}
    pre {{
      overflow: auto;
      padding: 14px;
      border: 1px solid var(--line);
      background: var(--panel);
    }}
    .summary {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
      gap: 12px;
      margin-top: 20px;
    }}
    .metric {{
      border: 1px solid var(--line);
      padding: 14px;
      background: var(--panel);
    }}
    .metric strong {{
      display: block;
      color: var(--accent);
      font-size: 24px;
    }}
  </style>
</head>
<body>
<main>
  <h1>{safe_title}</h1>
  <p>Self-contained topology inspection dashboard generated by Topological ML Toolkit.</p>
  <section class="summary">
    <div class="metric"><span>Finite bars</span><strong>{_finite_bar_count(diagram)}</strong></div>
    <div class="metric"><span>Feature rows</span><strong>{_matrix_shape(feature_matrix)[0]}</strong></div>
    <div class="metric"><span>Feature columns</span><strong>{_matrix_shape(feature_matrix)[1]}</strong></div>
  </section>
  <section>
    <h2>Persistence Diagram</h2>
    {diagram_rows}
  </section>
  <section>
    <h2>Feature Matrix</h2>
    {matrix_rows}
  </section>
  <section>
    <h2>Metadata</h2>
    <pre>{metadata_json}</pre>
  </section>
</main>
</body>
</html>
"""


def _diagram_rows(diagram: PersistenceDiagram | None) -> str:
    if diagram is None:
        return "<p>No persistence diagram supplied.</p>"
    rows = "\n".join(
        f"<tr><td>{pair.dimension}</td><td>{pair.birth:g}</td><td>{'inf' if pair.death is None else f'{pair.death:g}'}</td></tr>"
        for pair in diagram.pairs
    )
    return f"<table><thead><tr><th>Dimension</th><th>Birth</th><th>Death</th></tr></thead><tbody>{rows}</tbody></table>"


def _matrix_rows(feature_matrix: np.ndarray | None) -> str:
    if feature_matrix is None:
        return "<p>No feature matrix supplied.</p>"
    matrix = np.asarray(feature_matrix, dtype=float)
    rows = "\n".join(
        "<tr>" + "".join(f"<td>{value:g}</td>" for value in row) + "</tr>" for row in matrix
    )
    headers = "".join(f"<th>f{idx}</th>" for idx in range(matrix.shape[1] if matrix.ndim == 2 else 0))
    return f"<table><thead><tr>{headers}</tr></thead><tbody>{rows}</tbody></table>"


def _finite_bar_count(diagram: PersistenceDiagram | None) -> int:
    return 0 if diagram is None else len(diagram.finite_pairs())


def _matrix_shape(feature_matrix: np.ndarray | None) -> tuple[int, int]:
    if feature_matrix is None:
        return (0, 0)
    matrix = np.asarray(feature_matrix)
    if matrix.ndim != 2:
        return (0, 0)
    return (int(matrix.shape[0]), int(matrix.shape[1]))
